### ISSUE TITLE
Category Templates Not Compiling To Right Destination

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/site#7]
@doowb After the Assemble update to the latest version and switching to Node 6.10.2 the category templates no longer compile.

Here's the chunk that we added to the gulp file for that ability https://github.com/grayghostvisuals/site/blob/development/gulpfile.js#L168-L344

Essentially the "clients" folder no longer receives the compiled html from their handlebars file and goes into the root folder i.e. "site" not "clients"

**Comment by doowb** [comment]
Thanks for the issue, I'll take a look today.

**Comment by grayghostvisuals** [comment]
@doowb TY sir. Appreciate your time to jump in and offer a solution.

**Comment by doowb** [comment]
It looks like there was a bug that was fixed in one of the underlying modules but the versions haven't been updated yet in `assemble-permalinks`. I'll try to get that updated and published soon, then there'll be a small change in the permalink pattern.

**Comment by grayghostvisuals** [comment]
@doowb Thanks for checking on that. I'm trying to launch my site this week so any idea when that fix can be pushed to assemble-permalinks?

**Comment by doowb** [comment]
@grayghostvisuals I published `assemble-permalinks@0.6.0` that has the latest sub-modules necessary to fix the bug. Now, you should only have to change [this line](https://github.com/grayghostvisuals/site/blob/development/gulpfile.js#L260) to remove the `()` from `:categories`. The link will look like `app.create('pages').use(permalinks(':category:name.html', {`

If you have any questions, let me know. I did this as a minor bump (still below `1.0.0`) to ensure anyone else's existing builds don't change and didn't go up to `1.0.0` because we're working on a refactor of `permalinks` and `assemble-permalinks` that will be easier and more flexible.

**Comment by grayghostvisuals** [comment]
@doowb Thanks for the update.
